### ISSUE TITLE
Application for Prototype Fund

### ISSUE THREAD

**Issue by pmeising** [debsdebsenson/I2C#3]

**Comment by pmeising** [comment]
Hab das mal in ein Issue verwandelt, damit ich hier kommentieren kann :P @debsdebsenson 
1. Dein Link reicht erst mal aus.
2. Für die Beschreibung des Projektes könnten wir den Elevator pitch nehmen: With the help of I2C a possibility is to be offered to establish a communication over pictures by eye movement. For this purpose a table-like structure is used, in which e.g. 8 pictures are shown on a screen, by eye movement for example to the left the 4 pictures on the left side of the screen are selected and distributed on the screen, this can be repeated until the suitable picture was selected. This is intended to serve as a communication interface for people who can neither speak nor read, but can recognize images. The goal is to provide a simple and time and nerve saving solution for the person preparing the app.
3. Als Projekte, an denen ich gearbeitet habe, würde ich definitiv 42 Wolfsburg angeben. https://github.com/pmeising/42Wolfsburg_Core_Curriculum

**Comment by debsdebsenson** [comment]
Hi, verstehe ich, finde ich aber nicht so gut, weil das jetzt die ganze Welt mitlesen kann. Hab den Inhalt entfernt.
