### ISSUE TITLE
Think about a database to run locally for storing the images and other data.

### ISSUE THREAD

**Issue by pmeising** [debsdebsenson/I2C#4]

**Comment by pmeising** [comment]
Having a separate database installed is probably overkill. We are probably only going to realistically need about 64 images initially, which do not have to be of the highest resolution and therefore wouldn't be using up too much space anyway stored in a folder.

**Comment by debsdebsenson** [comment]
I think you're right. I found this about [storaging with kivy]( https://kivy.org/doc/stable/api-kivy.storage.html). This would be the module of my choice: "[kivy.storage.jsonstore.JsonStore](https://kivy.org/doc/stable/api-kivy.storage.jsonstore.html#kivy.storage.jsonstore.JsonStore): use a [JSON](https://en.wikipedia.org/wiki/JSON) file as a store".

**Comment by debsdebsenson** [comment]
I'll open a separate issue for implementing this.
